runtime: nodejs18
env: standard

handlers:
  - url: /(.*\.(js|css|png|jpg|svg|ico|json|html))$
    static_files: build/\1
    upload: build/(.*)

  - url: /.*
    static_files: build/index.html
    upload: build/index.html
