steps:
  # Step 1: Install dependencies
  - name: 'gcr.io/cloud-builders/npm'
    args: ['install']

  # Step 2: Build the React app
  - name: 'gcr.io/cloud-builders/npm'
    args: ['run', 'build']

  # Step 3: Deploy to App Engine using Cloud SDK
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args: ['app', 'deploy', '--quiet']

timeout: '1200s'

options:
  logging: CLOUD_LOGGING_ONLY
